alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table user_task_history drop foreign key FKt9srh5xryipkkj7p2bl867kt6;
alter table user_task_history drop foreign key FKldvbuyquy1qayg2gu24xwcvc7;
drop table if exists event;
drop table if exists task;
drop table if exists user;
drop table if exists user_task_history;
alter table task drop foreign key FK7ilhurfgk0scjjdcym9gtfvc8;
drop table if exists event;
drop table if exists task;
drop table if exists user;
alter table task drop foreign key FK7ilhurfgk0scjjdcym9gtfvc8;
drop table if exists event;
drop table if exists task;
drop table if exists user;
alter table task drop foreign key FK7ilhurfgk0scjjdcym9gtfvc8;
drop table if exists event;
drop table if exists task;
drop table if exists user;
alter table task drop foreign key FK7ilhurfgk0scjjdcym9gtfvc8;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table task drop foreign key FK7ilhurfgk0scjjdcym9gtfvc8;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table task drop foreign key FK7ilhurfgk0scjjdcym9gtfvc8;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table task drop foreign key FK7ilhurfgk0scjjdcym9gtfvc8;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
