alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user drop foreign key FKscghiysqkkrk5g011wwuydw2u;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
alter table user_event drop foreign key FKspe8srtv69gubpphvrnd7wekt;
alter table user_event drop foreign key FKk3smcqwou8absq8qjt3wk4vy9;
drop table if exists event;
drop table if exists goal;
drop table if exists task;
drop table if exists user;
drop table if exists user_event;
